console.log("By Addition (5+3) \n");
var resultbyadd = 5 + 3;
console.log(resultbyadd + "\n");
console.log("By Substraction (16-8) \n");
var resultbysub = 16 - 8;
console.log(resultbysub + "\n");
console.log("By Multiplication (4*2) \n");
var resultbymul = 4 * 2;
console.log(resultbymul + "\n");
console.log("By Division (64/8) \n");
var resultbydiv = 64 / 8;
console.log(resultbydiv);
